In [158]:
import numpy as np 

In [2]:
arr1 = np.array([11,21,31,41,49])

In [3]:
arr1

array([11, 21, 31, 41, 49])

In [25]:
arr1.ndim

1

In [5]:
arr2 = np.array([[1,9,21],[29,41,51],[58,72,8]])

In [6]:
arr2

array([[ 1,  9, 21],
       [29, 41, 51],
       [58, 72,  8]])

In [26]:
arr2.ndim

2

In [7]:
arr3 = np.array([[15,7,10,-11,20,75],[-3,9,24,1,100,-14]])

In [8]:
arr3

array([[ 15,   7,  10, -11,  20,  75],
       [ -3,   9,  24,   1, 100, -14]])

In [27]:
arr3.ndim

2

In [9]:
arr1.sum()

153

In [10]:
arr2.sum()

290

In [11]:
arr3.sum()

233

In [12]:
arr2.sum(axis = 0) ## row wise addition

array([ 88, 122,  80])

In [13]:
arr2.sum(axis = 1) ## column wise addition

array([ 31, 121, 138])

In [14]:
arr3.sum(axis = 0)

array([ 12,  16,  34, -10, 120,  61])

In [15]:
arr3.sum(axis = 1)

array([116, 117])

In [16]:
np.average(arr1)

30.6

In [24]:
np.average(arr1,1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [17]:
np.average(arr2)

32.22222222222222

In [18]:
np.average(arr3)

19.416666666666668

In [19]:
np.average(arr2,axis = 0)

array([29.33333333, 40.66666667, 26.66666667])

In [20]:
np.average(arr2,axis = 1)

array([10.33333333, 40.33333333, 46.        ])

In [21]:
np.average(arr3,axis = 0)

array([ 6. ,  8. , 17. , -5. , 60. , 30.5])

In [23]:
np.average(arr3,0)

array([ 6. ,  8. , 17. , -5. , 60. , 30.5])

In [22]:
np.average(arr3,axis = 1) ##or np.average(arr3,1)

array([19.33333333, 19.5       ])

In [28]:
arr1.min()

11

In [29]:
arr2.min()

1

In [30]:
arr3.min()

-14

In [31]:
arr1.max()

49

In [36]:
arr2.max()

72

In [37]:
arr3.max()

100

In [34]:
arr1.max(axis = 0)

49

In [38]:
arr2.max(axis = 0)

array([58, 72, 51])

In [39]:
arr3.max(axis = 0)

array([ 15,   9,  24,   1, 100,  75])

In [40]:
arr1.max(axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [41]:
arr2.max(axis = 1) ## or arr2.miax(1)

array([21, 51, 72])

In [42]:
arr3.max(axis = 1)

array([ 75, 100])

In [43]:
arr1.mean()

30.6

In [44]:
arr2.mean()

32.22222222222222

In [45]:
arr3.mean()

19.416666666666668

In [46]:
arr1.mean(1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [47]:
arr2.mean(1) ##col wise mean

array([10.33333333, 40.33333333, 46.        ])

In [49]:
arr2

array([[ 1,  9, 21],
       [29, 41, 51],
       [58, 72,  8]])

In [48]:
arr3.mean(1) column wise mean

array([19.33333333, 19.5       ])

In [50]:
### Computation on Arrays: Broadcasting

The term broadcasting refers to how numpy treats arrays with different Dimension
while arithmetic operations leading to specific constraints. Moreover, the smaller arrayis broadcast across the larger array so that they have compatible shapes

Broadcasting provides a means of vectorising array operations so that looping occurs in C rather than Python as we understand that Numpy implemented in C programming
language

It does this without creating unnecessary data copies and which leads to efficient
algorithm implementations

In some cases, broadcasting is a bad idea because it leads to ineffective memory
utilisation which declines the computation

In [53]:
a1 = np.array([1,3,7,5])
b1 = np.array([90,50,0,30])

In [54]:
c1 = a1 * b1

In [55]:
c1

array([ 90, 150,   0, 150])

In [56]:
d1 = 3

In [57]:
e1 = a1 * d1

In [58]:
e1

array([ 3,  9, 21, 15])

In [59]:
f1 = a1 + d1

In [60]:
f1

array([ 4,  6, 10,  8])

Broadcasting Rules:
• The following are the rules in order to broadcast two arrays together:
1. Prepend the shape of the lower rank array with 1s until both shapes have the same
length if the arrays do not have the same rank
2. In a dimension, the two arrays are compatible if they have the same size in the
dimension or if one of the arrays has size 1 in that dimension
3. If arrays are compatible with all dimensions then they can be broadcasted together
4. After broadcasting, every array acts as if it had shape equivalent to the element‐wise maximum of shapes of the two input arrays
5. In any dimension where one array had size 1, as well as the other array had size greater than 1, the first array acts as if it were copied along that dimension

In [61]:
a1 =np.array([[12,23,34],[11,21,31]])

In [62]:
a1

array([[12, 23, 34],
       [11, 21, 31]])

In [63]:
b1 = 4

In [64]:
b1

4

In [65]:
c1 = a1 + b1

In [66]:
c1

array([[16, 27, 38],
       [15, 25, 35]])

In [75]:
a1= np.array([1,3,5,7])
d1= np.array([1,5,5,3])

In [76]:
e1= d1*a1

In [78]:
e1

array([ 1, 15, 25, 21])

random function

A two‐dimensional array is generated by the first array having a size of 5 rows and 
columns, and the values are within 10 and 50

A random three‐dimensional array of size 2*3*6 is generated by this second array. The
generated random values are within 1 and 20

In [92]:
arr_random = np.random.randint(10, 50, size = (5, 8))

In [93]:
arr_random

array([[18, 39, 41, 32, 43, 35, 42, 38],
       [15, 21, 20, 26, 30, 41, 43, 44],
       [30, 23, 40, 28, 47, 25, 37, 18],
       [10, 21, 35, 42, 32, 40, 28, 12],
       [12, 43, 45, 23, 18, 39, 34, 32]])

In [100]:
arr2_rand = np.random.randint(1, 20, size = (2, 3, 6))

In [101]:
arr2_rand

array([[[ 2, 12, 18, 15, 19, 16],
        [12,  4,  6,  7, 16,  5],
        [13, 10, 16,  3, 19, 19]],

       [[10, 12,  3,  1,  8, 18],
        [ 1,  7, 17, 17, 11, 12],
        [ 8, 17,  9, 18,  2,  7]]])

In [97]:
arr2_rand.ndim

3

In [102]:
a = np.array([0,2,3,0,1,6,5,2])

In [103]:
np.greater(a,2)

array([False, False,  True, False, False,  True,  True, False])

In [104]:
np.greater_equal(a,2)

array([False,  True,  True, False, False,  True,  True,  True])

In [105]:
np.less(a,2)

array([ True, False, False,  True,  True, False, False, False])

In [106]:
np.less_equal(a,2)

array([ True,  True, False,  True,  True, False, False,  True])

In [107]:
a =np.reshape(np.arange(25),(5,5))

In [108]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [109]:
greater_values = (a > 10)

In [110]:
greater_values

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [112]:
even_values = (a%2==0)
odd_values = (a%2!=0)

In [113]:
even_values,odd_values

(array([[ True, False,  True, False,  True],
        [False,  True, False,  True, False],
        [ True, False,  True, False,  True],
        [False,  True, False,  True, False],
        [ True, False,  True, False,  True]]),
 array([[False,  True, False,  True, False],
        [ True, False,  True, False,  True],
        [False,  True, False,  True, False],
        [ True, False,  True, False,  True],
        [False,  True, False,  True, False]]))

In [114]:
b = ~(a%10 == 0)

In [115]:
b

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [116]:
c = (a%2 == 0) | (a%3 == 0)

In [117]:
c

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False,  True]])

In [119]:
d = (a%2 == 0) & (a%3 == 0)

In [120]:
d

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

----------------------------------MASKING IN NUMPYSS--------------------------------

In numpy.ma.mask_rows() function, mask rows of a 2‐Dimensional array which hold
masked values. The numpy.ma.mask_rows() function is a shortcut to mask_rowcols
with axis equal to 0

In [121]:
import numpy as np
import numpy.ma as MA ## this is not mandatory

In [123]:
array = np.zeros((4,4),dtype = int)

In [124]:
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [127]:
array[2,2] = 1

In [128]:
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [129]:
array = MA.masked_equal(array,1)

In [130]:
array

masked_array(
  data=[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, --, 0],
        [0, 0, 0, 0]],
  mask=[[False, False, False, False],
        [False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False]],
  fill_value=1)

In [134]:
masked_rows = MA.mask_rows(array)

In [135]:
masked_rows

masked_array(
  data=[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [--, --, --, --],
        [0, 0, 0, 0]],
  mask=[[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [False, False, False, False]],
  fill_value=1)

In [136]:
masked_rows_cols = MA.mask_rowcols(array)

In [137]:
masked_rows_cols

masked_array(
  data=[[0, 0, --, 0],
        [0, 0, --, 0],
        [--, --, --, --],
        [0, 0, --, 0]],
  mask=[[False, False,  True, False],
        [False, False,  True, False],
        [ True,  True,  True,  True],
        [False, False,  True, False]],
  fill_value=1)

In [139]:
arr2

array([[ 1,  9, 21],
       [29, 41, 51],
       [58, 72,  8]])

In [140]:
arr2 = MA.masked_equal(arr2,58)

In [141]:
arr2

masked_array(
  data=[[1, 9, 21],
        [29, 41, 51],
        [--, 72, 8]],
  mask=[[False, False, False],
        [False, False, False],
        [ True, False, False]],
  fill_value=58)

In [142]:
arr2_rows = MA.mask_rows(arr2)

In [143]:
arr2_rows

masked_array(
  data=[[1, 9, 21],
        [29, 41, 51],
        [--, --, --]],
  mask=[[False, False, False],
        [False, False, False],
        [ True,  True,  True]],
  fill_value=58)

In [144]:
arr2_rows_cols = MA.mask_rowcols(arr2)

In [145]:
arr2_rows_cols

masked_array(
  data=[[--, 9, 21],
        [--, 41, 51],
        [--, --, --]],
  mask=[[ True, False, False],
        [ True, False, False],
        [ True,  True,  True]],
  fill_value=58)

---------------------------------- FANCY INDEXING --------------------------------

• Fancy indexing is like the simple indexing, but we pass arrays of indices instead of single scalars
• It permits us to quickly access as well as change complicated subsets of an array's values

Exploring Fancy Indexing

• Fancy indexing is conceptually simple which means passing an array of indices in order to access multiple array elements at one time

• For instance, consider the below‐written array:

In [148]:
x = np.random.randint(100,size = 10)

In [149]:
x

array([ 6,  2, 24, 45, 76, 98,  9, 85, 19, 38])

• Let us suppose, we want to access three different elements
         [x[3],x[7],x[2]]

In [150]:
 [x[3],x[7],x[2]]

[45, 85, 24]

On the other hand, we can pass an array of indices or a single list for getting the same result:

In [152]:
ind1 = [3,7,4]
x[ind1]

array([45, 85, 76])

• While utilising fancy indexing, the shape of the result reflects the shape of the index varrays instead of the shape of the array being indexed:

In [153]:
ind2 = np.array([[3,7],[4,5]])
x[ind2]

array([[45, 85],
       [76, 98]])

• Even fancy indexing works in multiple dimensions. See the example shown below:

In [159]:
y = np.arange(12).reshape((3,4))

In [160]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

The first index refers to the row, and the second to the column Like with standard
indexing:

In [161]:
row = np.array([0,1,2])
col = np.array([2,1,3])
y[row,col]

array([ 2,  5, 11])

• The broadcasting rules are followed by the pairing of indices in fancy indexing.

Therefore, for instance, we get a two‐dimensional result if we combine a column vector
as well as a row vector within the indices:

In [163]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
y[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

• It is always necessary to memorise with fancy indexing that the broadcasted shape of
the indices is reflected by the return value, instead of the shape of the array being
indexed

Combined Indexing

• Fancy indexing can be combined with the other indexing schemes for more powerful
operations:

• We can combine fancy indexing with slicing as well:

• Even, fancy indexing can be combined with masking:

• All of these indexing options combined lead to a very flexible group of operations for accessing as well as modifying array values

In [165]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
y[2,[2,0,3]]

array([10,  8, 11])

In [168]:
y[1:,[2,0,3]]

array([[ 6,  4,  7],
       [10,  8, 11]])

In [181]:
mask = np.array([0,0,1,0],dtype = bool)

In [182]:
mask

array([False, False,  True, False])

In [183]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
y[row[:,np.newaxis],mask]

array([[ 2],
       [ 6],
       [10]])

Modifying Values with Fancy Indexing

• Fancy indexing can be used for accessing parts of an array. Moreover, it can modify parts of an array as well. For instance, assume we have an array of indices, and we want to set similar items in an array to some value:

•

In [187]:
a = np.arange(10)
i = np.array([2,1,8,4])
##a[i] = 99
a[i] -= 10
print(a)

[ 0 -9 -8  3 -6  5  6  7 -2  9]


Notice that, repeated indices with these operations can cause some potentially
unexpected outcomes

The outcome of this operation is to first assign A[0] = 8, followed by A[0] = 23. The result is that A[0] contains the value 23

In [189]:
a = np.zeros(10)
a[[0,0]] = [8,23]
print(a)

[23.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [193]:
array_num = np.array([5,7,2,8])

In [194]:
print(np.sort(array_num))

[2 5 7 8]


In [197]:
array_name = np.array(['pine-apple','banana','fig'])

In [202]:
print(np.sort(array_name))

['banana' 'fig' 'pine-apple']


In [199]:
array_bool = np.array([False,True,False])

In [200]:
print(np.sort(array_bool))

[False False  True]


In [204]:
array_sort_2d = np.array([[5,0,1],[9,3,6]])

In [205]:
print(np.sort(array_sort_2d))

[[0 1 5]
 [3 6 9]]


----------------------NumPy’s Structured Array-----------------------

• Numpy’s Structured Array is similar to Struct in C programming language. It is used in
order to group data of different sizes and types

• Data containers named as fields are used by the structure array. Every data field can
contain data of any size and type. With the help of dot notation, array elements can be
accessed

Structured Array Properties

• All structs in the array have the similar number of fields

• All structs have same fields names

• For instance, consider a student's structured array with different fields such as year,name, and marks

• Every record in array student has a structure of class Struct. Moreover, the array of a  structure is referred to as struct as adding any new fields for a new struct in the array, contains the empty array

In [207]:
import numpy as np

In [229]:
a1 = np.array([('Anand',2022,8.88),('Anil',2021,9.88) ,('Shubham',2020,8.90)],
              dtype = [('name',(np.str_,10)),('year',np.int32),('cgpa',np.float64)])

In [230]:
print(a1)

[('Anand', 2022, 8.88) ('Anil', 2021, 9.88) ('Shubham', 2020, 8.9 )]


In [231]:
a1[0][0]

'Anand'

In [236]:
a1[a1['name']=='shubham']

array([], dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [232]:
a1['name'] == 'Shubham'

array([False, False,  True])

In [228]:
a1[a1['name']=='Shubham']

array([('Shubham', 2022, 8.88), ('Shubham', 2021, 9.88),
       ('Shubham', 2020, 8.9 )],
      dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [210]:
b = np.sort(a1,order='name')

In [211]:
b

array([('Anand', 2022, 8.88), ('Anil', 2021, 9.88),
       ('Shubham', 2020, 8.9 )],
      dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [213]:
c = np.sort(a1,order='year')
c

array([('Shubham', 2020, 8.9 ), ('Anil', 2021, 9.88),
       ('Anand', 2022, 8.88)],
      dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [214]:
d = np.sort(a1,order='cgpa')
d

array([('Anand', 2022, 8.88), ('Shubham', 2020, 8.9 ),
       ('Anil', 2021, 9.88)],
      dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [235]:
names = a1.name

AttributeError: 'numpy.ndarray' object has no attribute 'name'